var EventDispatcher = function(eventKeyList) {};
EventDispatcher.prototype.all;
EventDispatcher.prototype.clear;
EventDispatcher.prototype.clearAll;
EventDispatcher.prototype.dispatch ;
EventDispatcher.prototype.filt ;
EventDispatcher.prototype.off ;
EventDispatcher.prototype.on ;
EventDispatcher.prototype.once ;
EventDispatcher.prototype.times;
