var EventDispatcher = function(eventKeyList) {};
EventDispatcher.prototype.all;
EventDispatcher.prototype.clearListenersByKey;
EventDispatcher.prototype.clearAllListeners;
EventDispatcher.prototype.dispatchEvent ;
EventDispatcher.prototype.filt ;
EventDispatcher.prototype.off ;
EventDispatcher.prototype.on ;
EventDispatcher.prototype.once ;
EventDispatcher.prototype.times;
